### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by thunderdome2** [sebastianbrunnert/GoogleTools-Desktop#2]
Hello.

The desktop notifications could be a great enhancement.

Regards.

**Comment by sebastianbrunnert** [comment]
Hey,
Great idea.

What do you mean, where should the user be notified?

**Comment by thunderdome2** [comment]
Hello.

Here's an example:
When I receive a calendar event, Chrome send me a notification on my desktop. I expect the same behaviour with this app. I think that will use the Electron desktop notification https://electronjs.org/docs/tutorial/notifications
