### ISSUE TITLE
Open links in another app

### ISSUE THREAD

**Issue by thunderdome2** [sebastianbrunnert/GoogleTools-Desktop#3]
Hello.

When I want to open a link from my emails inside GoogleTools-Desktop, I'm "locked" into the app:
![image](https://user-images.githubusercontent.com/27619936/66302625-8822e600-e8f9-11e9-9c1e-25a218130e55.png)

With another app (namely Wavebox), I have the choice which app will open my link:
![wavebox-open-app](https://user-images.githubusercontent.com/27619936/66306878-19e32100-e903-11e9-8a3b-a6baa0b9b5cf.jpg)

This behaviour is about links, but maybe about "mailto:" or any other concerns.

Thanks for your help.
Regards.

**Comment by sebastianbrunnert** [comment]
Done, will be there in next version :)
