### ISSUE TITLE
Couldn't sign you in

### ISSUE THREAD

**Issue by djalmasilvajr** [sebastianbrunnert/GoogleTools-Desktop#4]
I'am on Ubuntu Desktop 19.10, on Samsaung Expert 30.  After instaling and try to open one of the apps, like Keep, it redirects me to the login page, and after I give my credentials ( that I use every day ) the app show this error:
![Captura de tela de 2020-01-18 22-22-46](https://user-images.githubusercontent.com/1001772/72673210-f2453e00-3a45-11ea-9007-d90913acf12b.png)
Couldn't sign you in
This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by sebastianbrunnert** [comment]
Hey,
I already know about this bug. I will fix it soon.
Thank you

**Comment by sebastianbrunnert** [comment]
"Fixed it" :D
Look at the README
